version: "3.9"
services:
  server1:
    build: .
    environment:
      - server_name=server1
    command: python server.py
    container_name: server1

  
  server2:
    build: .
    environment:
      - server_name=server2
    command: python server.py
    container_name: server2
  
  server3:
    build: .
    environment:
      - server_name=server3
    command: python server.py
    container_name: server3
  server4:
    build: .
    environment:
      - server_name=server4
    command: python server.py
    container_name: server4

  server5:
    build: .
    environment:
      - server_name=server5
    command: python server.py
    container_name: server5

  client:
    build: .
    command: tail -f /dev/null
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - server5
