version: "3.9"
services:
  server:
    build: .
    environment:
      - server_name=server1
    command: python server.py
    container_name: server1
    ports:
    - "5000:5000"
  
  server2:
    build: .
    environment:
      - server_name=server2
    command: python server.py
    container_name: server2
    ports:
    - "5000:5000"
  
  server3:
    build: .
    environment:
      - server_name=server3
    command: python server.py
    container_name: server3
    ports:
    - "5000:5000"
  client:
    build: .
    command: python client.py
    depends_on:
      - server
