version: "3.9"
services:
  server:
    build: .
    command: python multicast_reciver.py
    container_name: multicast_reciver1
    ports:
    - "5007:5007"
  server2:
    build: .
    command: python multicast_reciver.py
    container_name: multicast_reciver2
    ports:
    - "5007:5007"

  server3:
    build: .
    command: python multicast_reciver.py
    container_name: multicast_reciver1
    ports:
    - "5007:5007"

  client:
    build: .
    command: python multicast_sender.py
    depends_on:
      - server

  client2:
      build: .
      command: python multicast_sender.py
      depends_on:
        - server