version: "3.9"
services:
  sender1:
    build: .
    command: python multicast_reciver.py
    container_name: multicast_reciver1
    ports:
    - "5007:5007"
  sender2:
    build: .
    command: python multicast_reciver.py
    container_name: multicast_reciver2
    ports:
    - "5007:5007"

  sender3:
    build: .
    command: python multicast_reciver.py
    container_name: multicast_reciver3
    ports:
    - "5007:5007"

  receiver1:
    build: .
    command: python multicast_sender.py
    depends_on:
      - sender

  receiver2:
      build: .
      command: python multicast_sender.py
      depends_on:
        - sender