version: "3.9"
services:
  sender1:
    build: .
    command: python multicast_reciver.py
    container_name: multicast_reciver1
    environment:
      -sensor=temp
    networks:
      - mnet
  sender2:
    build: .
    command: python multicast_reciver.py
    container_name: multicast_reciver2
    environment:
      -sensor=humidity
    networks:
      - mnet

  receiver1:
    build: .
    command: python multicast_sender.py
    networks:
      - mnet

  receiver2:
      build: .
      command: python multicast_sender.py
      networks:
        - mnet
networks:
  mnet: