services:
  sender1:
    build: .
    command: python multicast_sender.py
    container_name: sender1
    environment:
      - SENSOR_NAME=temp
    network_mode: "host"

  sender2:
    build: .
    command: python multicast_sender.py
    container_name: sender2
    environment:
      - SENSOR_NAME=humidity
    network_mode: "host"

  receiver1:
    build: .
    command: python multicast_receiver.py --duration 15
    container_name: receiver1
    network_mode: "host"
    depends_on:
      - sender1
      - sender2

  receiver2:
    build: .
    command: python multicast_receiver.py --duration 15
    container_name: receiver2
    network_mode: "host"
    depends_on:
      - sender1
      - sender2
  monitor:
    image: nicolaka/netshoot
    command: tcpdump -i eth0 udp port 5007 -n
    network_mode: "host"