version: "3.9"

services:
  server:
    build: ./task6_server
    container_name: my_server
    ports:
      - "5000:5000/tcp"

  client1:
    build: ./task6_client
    depends_on:
      - server

  client2:
    build: ./task6_client
    depends_on:
      - server

  client3:
    build: ./task6_client
    depends_on:
      - server
